import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import {
  ArrowLeft, ArrowRight, BookOpen, Bot, BriefcaseBusiness, CalendarDays, Camera,
  Check, ChevronDown, ClipboardCheck, Copy, HeartHandshake, Home, LockKeyhole,
  Menu, MessageCircleHeart, Mic, MicOff, Monitor, Phone, Play, Send, Sparkles,
  Users, Video, VideoOff, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import counsellingImage from "@/assets/umeed-counselling.jpg";
import campusImage from "@/assets/umeed-campus.jpg";
import resourcesImage from "@/assets/umeed-resources.jpg";

const navItems = [
  { to: "/dashboard", label: "Dashboard", icon: Home },
  { to: "/quiz", label: "Stress Assessment", icon: ClipboardCheck },
  { to: "/counselling", label: "Professional Support", icon: HeartHandshake },
  { to: "/resources", label: "Wellness Resources", icon: BookOpen },
  { to: "/chat", label: "AI Support Chat", icon: Bot },
  { to: "/video", label: "Video Conference", icon: Video },
] as const;

function Brand({ compact = false }: { compact?: boolean }) {
  return <Link to="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary font-display text-xl text-primary-foreground shadow-soft">U</span>{!compact && <span><strong className="block font-display text-xl font-medium">UmeedBot</strong><small className="block text-xs text-muted-foreground">Student Wellness Assistant</small></span>}</Link>;
}

function AppShell({ children, active }: { children: React.ReactNode; active: string }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground">
    <Button variant="glass" size="icon" className="fixed left-4 top-4 z-50 lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu /></Button>
    {open && <button aria-label="Close navigation" className="fixed inset-0 z-40 bg-overlay lg:hidden" onClick={() => setOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-border/60 bg-surface/85 p-5 backdrop-blur-2xl transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-start justify-between"><Brand /><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(false)} aria-label="Close navigation"><X /></Button></div>
      <nav className="mt-10 flex flex-1 flex-col gap-1.5">
        {navItems.map(({to,label,icon:Icon}) => <Link key={to} to={to} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium transition-all ${active === to ? "bg-primary text-primary-foreground shadow-soft" : "text-muted-foreground hover:bg-accent hover:text-accent-foreground"}`}><Icon className="size-4" />{label}</Link>)}
      </nav>
      <div className="rounded-2xl bg-accent/70 p-4"><p className="font-display text-lg">You matter.</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Confidential support is available whenever you need it.</p></div>
    </aside>
    <main className="min-h-screen px-5 pb-16 pt-20 lg:ml-72 lg:px-10 lg:pt-10"><div className="mx-auto max-w-6xl">{children}</div></main>
  </div>;
}

const solutions = [
  ["AI-Guided First-Aid Support","Interactive chat system that offers immediate coping strategies and refers students to professionals when needed, available 24/7."],
  ["Confidential Booking System","Secure platform for students to book appointments with on-campus counsellors or mental health helplines without fear of stigma."],
  ["Psychoeducational Resource Hub","Comprehensive library of videos, relaxation audio, and mental wellness guides available in multiple regional languages."],
  ["Peer Support Platform","Moderated peer-to-peer support forum with trained student volunteers to foster community and reduce isolation."],
  ["Admin Dashboard","Anonymous data analytics for college authorities to recognize mental health trends and plan targeted interventions."],
  ["Cultural Context","Tailored content that considers regional cultural context and language, unlike generic Western-oriented solutions."],
];
const faqs = [
  ["How does UmeedBot ensure student privacy?","Student privacy is our top priority. All data is anonymized, conversations are encrypted, and we never share identifiable information. Students can use pseudonyms, and college administrators only see aggregated, anonymized data trends."],
  ["Can colleges customize UmeedBot for their specific needs?","Yes, UmeedBot is designed to be customizable. Colleges can add their counseling resources, set up specific peer support programs, and tailor content to their institutional context and regional requirements."],
  ["Is UmeedBot a replacement for professional counseling?","No, UmeedBot complements professional services by providing early intervention, resources, and support between sessions. It includes screening tools that can identify when professional help is needed and facilitates referrals."],
  ["How does the peer support system work?","Peer supporters are trained student volunteers who moderate forums and provide support. The system includes safeguards, moderation tools, and escalation protocols to ensure a safe environment for all participants."],
];

export function HomePage() {
  const [menu, setMenu] = useState(false);
  return <div className="overflow-hidden bg-background">
    <header className="sticky top-0 z-40 border-b border-border/50 bg-background/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Brand />
      <nav className="hidden items-center gap-7 md:flex">{[["#problem","The Problem"],["#solutions","Solutions"],["#process","How It Works"],["#testimonials","Testimonials"],["#faq","FAQ"]].map(([href,label])=><a key={href} href={href} className="text-sm text-muted-foreground transition-colors hover:text-primary">{label}</a>)}</nav>
      <div className="flex items-center gap-2"><Button asChild className="hidden sm:inline-flex"><Link to="/login">Student Login</Link></Button><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Toggle menu"><Menu /></Button></div>
    </div>{menu && <nav className="border-t border-border p-4 md:hidden">{["The Problem","Solutions","How It Works","Testimonials","FAQ"].map(x=><a key={x} className="block py-2 text-sm" href={`#${x.toLowerCase().replaceAll(" ","-")}`}>{x}</a>)}</nav>}</header>
    <section className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr]">
      <div className="pointer-events-none absolute -left-32 top-20 size-96 rounded-full bg-accent/50 blur-3xl" />
      <div className="relative"><span className="eyebrow"><Sparkles className="size-3" /> College mental health support</span><h1 className="mt-7 max-w-3xl font-display text-5xl leading-[1.02] md:text-7xl">Digital Mental Health Support for <span className="text-primary">College Students</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">UmeedBot provides a stigma-free, scalable psychological intervention system designed specifically for higher education institutions to address the growing mental health crisis among students.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/login">Student Portal <ArrowRight /></Link></Button><Button asChild variant="glass" size="lg"><a href="#process">Learn More</a></Button></div></div>
      <div className="relative mx-auto w-full max-w-lg"><div className="glass-panel p-3"><img src={counsellingImage} alt="A student speaking with a counsellor in a calm room" className="aspect-[4/5] w-full rounded-2xl object-cover" width={1088} height={1360}/></div><div className="absolute -bottom-6 left-3 rounded-2xl bg-surface/90 px-5 py-4 shadow-float backdrop-blur-xl sm:-left-6"><p className="font-display text-2xl text-primary">A safe first step</p><p className="text-xs text-muted-foreground">Private • Supportive • Available 24/7</p></div></div>
    </section>
    <section id="problem" className="section-band bg-surface"><SectionTitle eyebrow="Why it matters" title="The College Mental Health Crisis" copy="Mental health issues among college students have significantly increased, creating an urgent need for accessible, stigma-free support systems"/><div className="grid gap-5 md:grid-cols-3"><InfoCard title="The Gap in Support" copy="Most higher education institutions, especially in rural and semi-urban areas, lack structured, scalable psychological intervention systems that students can access without fear of judgment."/><InfoCard title="Rising Concerns" copy="Anxiety, depression, burnout, sleep disorders, academic stress, and social isolation are increasingly prevalent among college students, yet support resources remain limited."/><InfoCard title="Stigma & Awareness" copy="College counselling centers are often under-utilized due to fear of judgment, lack of awareness about available services, and concerns about confidentiality."/></div></section>
    <section id="solutions" className="section-band"><SectionTitle eyebrow="Our approach" title="Our Comprehensive Solution" copy="UmeedBot integrates multiple support mechanisms to create a holistic mental health ecosystem for colleges"/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{solutions.map(([title,copy],i)=><InfoCard key={title} number={i+1} title={title} copy={copy}/>)}</div></section>
    <section id="process" className="section-band bg-surface"><SectionTitle eyebrow="Simple by design" title="How UmeedBot Works" copy="A seamless integration process for colleges and easy access for students"/><div className="grid gap-4 md:grid-cols-4">{[["Institution Onboarding","Colleges register their counseling services and resources with the platform."],["Student Registration","Students create anonymous profiles using their college credentials."],["Access Support","Students can chat with AI, book appointments, or join peer forums."],["Admin Monitoring","College administrators access anonymized data to identify trends."]].map(([t,c],i)=><div className="p-6" key={t}><span className="font-display text-5xl text-primary/35">0{i+1}</span><h3 className="mt-3 font-display text-xl">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{c}</p></div>)}</div></section>
    <section id="testimonials" className="section-band"><SectionTitle eyebrow="Shared experience" title="What Students & Institutions Say" copy="Hear from those who have implemented or used UmeedBot"/><div className="grid gap-5 md:grid-cols-3">{[["As someone who struggled with anxiety throughout college, having a stigma-free platform like UmeedBot made all the difference. I could access support without fear of judgment from peers or professors.","Rahul Sharma","Engineering Student"],["The admin dashboard has given us unprecedented insights into student mental health trends. We've been able to implement targeted wellness programs that actually address student needs.","Dr. Anjali Mehta","Head of Student Welfare"],["The regional language resources make mental health support accessible to students from diverse backgrounds. This is something missing from most Western mental health apps.","Priya Reddy","Psychology Department"]].map(([q,n,r])=><blockquote className="glass-panel p-7" key={n}><p className="font-display text-xl leading-8">“{q}”</p><footer className="mt-6 text-sm"><strong>{n}</strong><span className="block text-muted-foreground">{r}</span></footer></blockquote>)}</div></section>
    <section id="faq" className="section-band bg-surface"><SectionTitle eyebrow="Clear answers" title="Frequently Asked Questions" copy="Common questions about implementing and using UmeedBot"/><div className="mx-auto max-w-3xl divide-y divide-border">{faqs.map(([q,a])=><details className="group py-5" key={q}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-display text-xl">{q}<ChevronDown className="size-5 transition-transform group-open:rotate-180"/></summary><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{a}</p></details>)}</div></section>
    <footer className="border-t border-border bg-foreground py-12 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-8 px-5 md:grid-cols-3"><div><Brand/><p className="mt-5 max-w-sm text-sm leading-6 opacity-70">UmeedBot is a digital psychological intervention system designed specifically for higher education institutions to address the growing mental health crisis among college students.</p></div><div><h3 className="font-display text-lg">Contact Us</h3><p className="mt-4 text-sm opacity-70">Email: support@umeedbot.edu<br/>Phone: (555) 123-HELP<br/>Address: 123 Education Lane, Campus City</p></div><div><h3 className="font-display text-lg">Ready to Transform Student Mental Health Support?</h3><Button asChild className="mt-4 bg-surface text-foreground hover:bg-surface/90"><Link to="/login">Student Login</Link></Button></div></div></footer>
  </div>;
}

function SectionTitle({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}) { return <div className="mb-10 max-w-2xl"><span className="eyebrow">{eyebrow}</span><h2 className="mt-4 font-display text-4xl md:text-5xl">{title}</h2><p className="mt-4 leading-7 text-muted-foreground">{copy}</p></div> }
function InfoCard({title,copy,number}:{title:string;copy:string;number?:number}) { return <article className="glass-panel p-7 transition-all hover:-translate-y-1 hover:shadow-float">{number && <span className="grid size-11 place-items-center rounded-xl bg-accent font-display text-lg text-primary">{number}</span>}<h3 className={`${number?"mt-5":""} font-display text-xl`}>{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article> }

export function LoginPage() { const [signup,setSignup]=useState(false); const [done,setDone]=useState(false); return <div className="relative grid min-h-screen place-items-center overflow-hidden bg-background p-5"><div className="absolute inset-0"><img src={campusImage} alt="Students walking together on campus" className="h-full w-full object-cover opacity-25" width={1408} height={912}/><div className="absolute inset-0 bg-background/60 backdrop-blur-sm"/></div><div className="relative w-full max-w-md glass-panel p-8 sm:p-10"><Brand/><div className="mt-8"><span className="eyebrow">Student Wellness Hub</span><h1 className="mt-4 font-display text-4xl">{signup?"Create Your Account":"Login to Your Account"}</h1><p className="mt-2 text-sm text-muted-foreground">Your path to mental wellness begins here</p></div>{done?<div className="mt-8 rounded-2xl bg-accent p-6 text-center"><Check className="mx-auto size-8 text-primary"/><p className="mt-3 font-display text-xl">Welcome to UmeedBot</p><Button asChild className="mt-5"><Link to="/dashboard">Continue to Dashboard</Link></Button></div>:<form className="mt-8 space-y-5" onSubmit={e=>{e.preventDefault();setDone(true)}}>{signup&&<Field label="Full Name"><Input required placeholder="Your full name"/></Field>}<Field label="Email Address"><Input required type="email" placeholder="you@college.edu"/></Field><Field label="Password"><Input required type="password" placeholder="Enter your password"/></Field><Button className="w-full" size="lg" type="submit">{signup?"Sign Up":"Login"}<ArrowRight/></Button><div className="flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><Button type="button" variant="glass" size="lg" className="w-full">Continue with Google</Button></form>}<p className="mt-7 text-center text-sm text-muted-foreground">{signup?"Already have an account?":"Don't have an account?"} <button className="font-semibold text-primary hover:underline" onClick={()=>setSignup(!signup)}>{signup?"Login":"Sign Up"}</button></p></div></div> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label> }

export function DashboardPage() { return <AppShell active="/dashboard"><PageIntro eyebrow="Your space" title="Employee Wellness Hub" copy="Your path to better work-life balance starts here"/><div className="grid gap-5 md:grid-cols-2">{[["/quiz",ClipboardCheck,"Workplace Stress Assessment","Take a quick assessment to understand your current stress levels"],["/counselling",HeartHandshake,"Professional Support","Book a confidential appointment with an employee assistance counselor"],["/resources",BookOpen,"Wellness Resources","Access helpful articles, stress management techniques, and work-life balance strategies"],["/chat",Bot,"AI Support Chat","Talk to our supportive AI assistant for immediate guidance"]].map(([to,I,title,copy])=>{const Icon=I as typeof Home;return <Link to={to as "/quiz"} key={String(title)} className="glass-panel group p-7 transition-all hover:-translate-y-1 hover:shadow-float"><Icon className="size-8 text-primary"/><h2 className="mt-5 font-display text-2xl">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(copy)}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">Open <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>})}</div><section className="mt-10 rounded-3xl bg-surface p-7"><h2 className="font-display text-3xl">About Our Assessment Tools</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{[["PHQ-9 (Depression)","A 9-item questionnaire that measures depression severity based on DSM-IV criteria."],["GAD-7 (Anxiety)","A 7-item scale that assesses anxiety symptoms and their severity."],["GHQ-12 (General Health)","A 12-item screening tool for detecting general psychological distress."]].map(([t,c])=><InfoCard key={t} title={t} copy={c}/>)}</div><p className="mt-6 text-sm text-muted-foreground">All assessments are confidential and designed to help identify areas where support may be beneficial.</p></section></AppShell> }

function PageIntro({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}) { return <header className="mb-9"><span className="eyebrow">{eyebrow}</span><h1 className="mt-4 font-display text-4xl md:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{copy}</p></header> }

const counsellors = [["Dr. Sarah Johnson","8+ years","Anxiety · Depression · Relationships","Dr. Johnson specializes in cognitive behavioral therapy and has helped hundreds of clients overcome anxiety and depression."],["Michael Rodriguez","12+ years","Trauma · PTSD · Mindfulness","Michael uses evidence-based approaches and compassionate guidance to help clients process trauma and build lasting resilience."],["Dr. Emily Chen","6+ years","Family Therapy · Teens · Communication","Dr. Chen specializes in family systems therapy and helping adolescents navigate life challenges."],["James Wilson","15+ years","Addiction · Recovery · Life Transitions","James has dedicated his career to supporting individuals through addiction recovery and major life changes."]];
export function CounsellingPage(){return <AppShell active="/counselling"><section className="grid items-center gap-8 lg:grid-cols-2"><div><span className="eyebrow">Professional support</span><h1 className="mt-5 font-display text-5xl leading-tight">Your Journey To <span className="text-primary">Mental Well-Being</span> Starts Here</h1><p className="mt-5 leading-7 text-muted-foreground">Connect with experienced, compassionate counsellors who understand your unique needs. Take the first step towards a healthier, happier you with our personalized therapy sessions.</p><div className="mt-7 flex gap-3"><Button asChild><Link to="/counselling-form">Book Session</Link></Button><Button asChild variant="glass"><a href="#counsellors">Learn More</a></Button></div></div><img src={counsellingImage} alt="A welcoming counselling conversation" className="aspect-[4/3] w-full rounded-3xl object-cover shadow-float" loading="lazy" width={1088} height={1360}/></section><div className="my-12 grid gap-4 md:grid-cols-3">{[["Licensed Professionals","Experienced, licensed counselors with verified credentials."],["Compassionate Care","Tailored personalized care for your specific needs and circumstances."],["Trusted Community","Join thousands of people who have healed and are leading better lives."]].map(([t,c])=><InfoCard key={t} title={t} copy={c}/>)}</div><section id="counsellors"><PageIntro eyebrow="Meet the team" title="Meet Our Professional Counsellors" copy="Our team of licensed professionals is here to support you on your journey to better mental health and personal growth."/><div className="grid gap-5 md:grid-cols-2">{counsellors.map(([name,exp,tags,bio],i)=><article key={name} className="glass-panel flex gap-5 p-6"><div className="grid size-14 shrink-0 place-items-center rounded-2xl bg-accent font-display text-xl text-primary">{name.split(" ").map(x=>x[0]).join("").slice(-2)}</div><div><h2 className="font-display text-2xl">{name}</h2><p className="mt-1 text-xs text-primary">Experience: {exp}</p><p className="mt-3 text-sm font-medium">{tags}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{bio}</p><Button asChild size="sm" className="mt-5"><Link to="/counselling-form" search={{ counsellor: String(i) }}>Book Appointment</Link></Button></div></article>)}</div></section></AppShell>}

export function CounsellingFormPage(){const [sent,setSent]=useState(false);return <div className="min-h-screen bg-background px-5 py-10"><div className="mx-auto max-w-3xl"><Link to="/counselling" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4"/>Back to counsellors</Link><div className="glass-panel overflow-hidden"><header className="bg-primary p-8 text-primary-foreground"><span className="text-xs font-semibold uppercase tracking-widest opacity-75">Counselling Form</span><h1 className="mt-3 font-display text-4xl">One Step Away From Your Come-back Session!</h1><p className="mt-2 opacity-80">Fill out the form below and our team will get back to you shortly</p></header>{sent?<div className="p-12 text-center"><Check className="mx-auto size-12 text-primary"/><h2 className="mt-4 font-display text-3xl">Your request has been received.</h2><p className="mt-3 text-muted-foreground">Our team will get back to you shortly.</p></div>:<form className="space-y-8 p-6 sm:p-9" onSubmit={e=>{e.preventDefault();setSent(true)}}><FormSection title="Personal Information"><div className="grid gap-5 sm:grid-cols-2"><Field label="Full Name"><Input required/></Field><Field label="Age"><Input required type="number"/></Field><SelectField label="Gender" options={["Select your gender","Male","Female","Other","Prefer not to say"]}/><SelectField label="Marital Status" options={["Select your marital status","Single","Married","Divorced","Widowed","Separated"]}/><Field label="Profession"><Input required/></Field></div></FormSection><FormSection title="Contact Details"><div className="grid gap-5 sm:grid-cols-2"><Field label="Email Address"><Input required type="email"/></Field><Field label="Mobile Number"><Input required type="tel"/></Field></div></FormSection><FormSection title="Appointment Details"><div className="grid gap-5 sm:grid-cols-2"><Field label="Appointment Date & Time"><Input required type="datetime-local"/></Field><SelectField label="Mode Of Appointment" options={["Select appointment type","Online Session (Video Call)","In-Person Session"]}/></div></FormSection><FormSection title="Additional Information"><Field label="Anything You'd Like To Share (Optional)"><Textarea className="min-h-28"/></Field></FormSection><label className="flex gap-3 text-sm leading-6 text-muted-foreground"><input required type="checkbox" className="mt-1 size-4 accent-primary"/>I agree to the Terms and Conditions and Privacy Policy. I understand that my information will be kept confidential and used solely for scheduling purposes.</label><Button type="submit" size="lg" className="w-full">Submit Your Request <ArrowRight/></Button></form>}</div></div></div>}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-5 font-display text-2xl text-primary">{title}</h2>{children}</section>}
function SelectField({label,options}:{label:string;options:string[]}){return <Field label={label}><select required className="h-11 w-full rounded-xl border border-input bg-surface/70 px-3 text-sm outline-none focus:ring-2 focus:ring-ring">{options.map(x=><option key={x}>{x}</option>)}</select></Field>}

const questions=["Do you feel more controlled by your own choices, or by others' expectations?","What drains you faster—your thoughts, your emotions, or the people around you?","Do your relationships recharge you, drain you, or leave you feeling unseen?","How do you usually handle stress—avoid, explode, hide, or overwork?","Do you crave more freedom, more love, more stability, or more recognition right now?","When you sit in silence, do you find peace, or do your thoughts attack you?","Do things you once enjoyed now feel pointless or flat?","Do you find yourself pulling away from people instead of reaching out?","Do you feel heavy inside, even when nothing bad just happened?","How often do you replay conversations, worrying what you said wrong?","How often do you avoid things because the ‘what ifs’ scare you?","How often do you feel like your existence doesn't make a difference?","Do you keep re-checking things (locks, messages, decisions) because doubt won't let go?","Do you worry more about what could happen than what is happening?","Do you constantly need reassurance, yet never fully believe it?"];
export function QuizPage(){const [answers,setAnswers]=useState<Record<number,number>>({});const [result,setResult]=useState(false);return <AppShell active="/quiz"><PageIntro eyebrow="Private self-check" title="Mood Self-Assessment Quiz" copy="Take a moment to reflect on your current emotional state. Rate each statement from 1 (low) to 5 (high)."/><div className="mb-7 h-2 overflow-hidden rounded-full bg-accent"><div className="h-full bg-primary transition-all" style={{width:`${Object.keys(answers).length/questions.length*100}%`}}/></div>{result?<Result score={Object.values(answers).reduce((a,b)=>a+b,0)/questions.length}/>:<div className="space-y-4">{questions.map((q,i)=><article className="glass-panel p-5 sm:flex sm:items-center sm:justify-between sm:gap-8" key={q}><div className="flex gap-4"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-accent font-display text-primary">{i+1}</span><p className="pt-1 leading-6">{q}</p></div><div className="mt-4 flex shrink-0 gap-2 sm:mt-0">{[1,2,3,4,5].map(n=><button aria-label={`Rate ${n}`} onClick={()=>setAnswers({...answers,[i]:n})} className={`grid size-9 place-items-center rounded-full text-sm transition-all ${answers[i]===n?"bg-primary text-primary-foreground shadow-soft":"bg-surface text-muted-foreground hover:bg-accent"}`} key={n}>{n}</button>)}</div></article>)}<Button size="lg" className="w-full" disabled={Object.keys(answers).length<questions.length} onClick={()=>setResult(true)}>Submit Assessment</Button></div>}</AppShell>}
function Result({score}:{score:number}){return <div className="glass-panel p-10 text-center"><Sparkles className="mx-auto size-12 text-primary"/><h2 className="mt-5 font-display text-3xl">Thank you for checking in.</h2><p className="mx-auto mt-3 max-w-xl text-muted-foreground">{score>3.5?"Your responses suggest things may feel heavy right now. Reaching out could help.":"Your responses show a relatively steady mood. Keep checking in with yourself."}</p><Button asChild className="mt-7"><Link to="/chat">Chat with our AI Counselor</Link></Button></div>}

export function ChatPage(){const [messages,setMessages]=useState<string[]>([]);const [text,setText]=useState("");const send=()=>{if(!text.trim())return;setMessages([...messages,text.trim()]);setText("")};return <AppShell active="/chat"><PageIntro eyebrow="Gemini Online" title="Gemini AI Student Counsellor" copy="Powered by Google Gemini • Available 24/7"/><div className="glass-panel flex min-h-[620px] flex-col overflow-hidden"><div className="flex items-center gap-3 border-b border-border p-5"><span className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground"><Bot/></span><div><h2 className="font-display text-xl">Welcome to UmeedBot 🤖</h2><p className="text-xs text-muted-foreground">Confidential & Secure • Available 24/7</p></div></div><div className="flex-1 space-y-4 overflow-y-auto p-5"><div className="max-w-xl rounded-2xl rounded-tl-sm bg-accent p-4 text-sm leading-6">I'm your AI-powered student support assistant.<br/>You can talk to me about academics, career, stress, motivation, or general concerns.<br/>How can I help you today?</div>{messages.map((m,i)=><div key={i} className="ml-auto max-w-xl rounded-2xl rounded-tr-sm bg-primary p-4 text-sm text-primary-foreground">{m}</div>)}</div><div className="border-t border-border p-4"><div className="flex items-end gap-3"><Textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask Gemini anything..." className="min-h-12 resize-none"/><Button size="icon" onClick={send} aria-label="Send message"><Send/></Button></div></div></div></AppShell>}

const categories=[["Career Counseling","Resources to help you navigate career challenges, find purpose, and achieve professional growth."],["Childhood Trauma","Understanding and healing from childhood experiences that continue to impact your life."],["Bad Relationships","Guidance on recognizing, addressing, and healing from unhealthy relationship patterns."],["Loneliness","Strategies to cope with loneliness and build meaningful connections with others."],["Financial Stress","Managing financial anxiety and developing healthy money habits for peace of mind."],["Identity Crisis / Self Worth","Exploring self-identity, building self-esteem, and finding your authentic self."]];
export function ResourcesPage(){const [selected,setSelected]=useState<string>();return <AppShell active="/resources">{selected?<><button className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary" onClick={()=>setSelected(undefined)}><ArrowLeft className="size-4"/>Back to Categories</button><PageIntro eyebrow="Category Videos" title={selected} copy="A carefully selected collection to support your personal growth journey."/><div className="grid gap-5 md:grid-cols-2">{Array.from({length:5},(_,i)=><article className="glass-panel overflow-hidden" key={i}><div className="relative aspect-video bg-accent"><img src={resourcesImage} alt="Calm wellness resources" className="h-full w-full object-cover opacity-80" loading="lazy" width={1408} height={912}/><span className="absolute inset-0 grid place-items-center"><span className="grid size-14 place-items-center rounded-full bg-surface/90 text-primary shadow-soft"><Play/></span></span></div><div className="p-5"><h2 className="font-display text-xl">{selected} — helpful practice {i+1}</h2><p className="mt-2 text-sm text-muted-foreground">A gentle, practical video to help you understand and navigate this experience.</p></div></article>)}</div></>:<><div className="grid items-center gap-7 lg:grid-cols-[1fr_.75fr]"><PageIntro eyebrow="Wellness library" title="Enhanced Counseling Resource Hub" copy="Explore our collection of helpful videos organized by category. Find the guidance you need for your personal growth journey."/><img src={resourcesImage} alt="A calm space with a journal and headphones" className="aspect-[16/8] w-full rounded-3xl object-cover shadow-soft" loading="lazy" width={1408} height={912}/></div><h2 className="mb-6 mt-10 font-display text-3xl">Counseling Categories</h2><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{categories.map(([t,c])=><button onClick={()=>setSelected(t)} key={t} className="glass-panel group p-7 text-left transition-all hover:-translate-y-1 hover:shadow-float"><BookOpen className="size-7 text-primary"/><h3 className="mt-5 font-display text-2xl">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{c}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">5 videos <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></button>)}</div></>}</AppShell>}

export function VideoPage(){const [joined,setJoined]=useState(false);const [mic,setMic]=useState(true);const [video,setVideo]=useState(true);const link=useMemo(()=>typeof window==="undefined"?"umeedbot.edu/meeting":window.location.href+"?room=umeed-care",[]);return <AppShell active="/video"><PageIntro eyebrow="Private video counselling" title="Umeed Bot Auto-Connect" copy="Signaling Handled Automatically via PeerJS"/><div className="glass-panel p-6"><div className="mb-6 rounded-2xl bg-accent p-4 text-sm"><strong>Status:</strong> {joined?"Media secured — waiting for your counsellor":"Initializing..."}</div>{joined&&<div className="mb-6 flex gap-2"><Input readOnly value={link}/><Button variant="glass" size="icon" aria-label="Copy meeting link" onClick={()=>navigator.clipboard?.writeText(link)}><Copy/></Button></div>}<div className="grid gap-5 lg:grid-cols-2">{["Your Stream","Remote Stream"].map((name,i)=><div className="relative grid aspect-video place-items-center overflow-hidden rounded-2xl bg-video" key={name}>{i===0&&joined&&video?<Camera className="size-12 text-primary-foreground/60"/>:<Users className="size-12 text-primary-foreground/35"/>}<span className="absolute bottom-3 left-3 rounded-lg bg-overlay px-3 py-1.5 text-xs text-primary-foreground">{name}</span></div>)}</div><div className="mt-6 flex flex-wrap justify-center gap-3">{!joined?<Button size="lg" onClick={()=>setJoined(true)}><Video/>1. Start or Join Meeting</Button>:<><Button variant="glass" size="icon" onClick={()=>setVideo(!video)} aria-label={video?"Turn video off":"Turn video on"}>{video?<VideoOff/>:<Video/>}</Button><Button variant="glass" size="icon" onClick={()=>setMic(!mic)} aria-label={mic?"Turn microphone off":"Turn microphone on"}>{mic?<MicOff/>:<Mic/>}</Button><Button variant="destructive" onClick={()=>setJoined(false)}><Phone/>End Meeting</Button></>}</div></div></AppShell>}